// Generated by commsdsl2comms v3.4.0

#pragma once

#include <QtCore/QVariantMap>

namespace ublox
{

namespace cc_plugin
{

namespace field
{

QVariantMap createProps_cfgDatMajA(const char* name, bool serHidden = false);

} // namespace field

} // namespace cc_plugin

} // namespace ublox


