// Generated by commsdsl2comms v3.6.4

#include "CfgValLayer.h"

#include "comms_champion/property/field.h"
#include "ublox/field/CfgValLayer.h"


namespace cc = comms_champion;

namespace ublox
{

namespace cc_plugin
{

namespace field
{

QVariantMap createProps_cfgValLayer(const char* name, bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ublox::field::CfgValLayer<>;
    return
        cc::property::field::ForField<Field>()
            .name(name)
            .serialisedHidden(serHidden)
            .add("RAM", 0)
            .add("BBR", 1)
            .add("Flash", 2)
            .add("Default", 7)
            .asMap();
    
}

} // namespace field

} // namespace cc_plugin

} // namespace ublox


