// Generated by commsdsl2comms v3.5.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::field::CfgDatD field.

#pragma once

namespace ublox
{

namespace field
{

/// @brief Common types and functions for
///     @ref ublox::field::CfgDatD field.
struct CfgDatDCommon
{
    /// @brief Re-definition of the value type used by
    ///     ublox::field::CfgDatD field.
    using ValueType = float;

    /// @brief Name of the @ref ublox::field::CfgDatD field.
    static const char* name()
    {
        return "cfgDatD";
    }
    
};

} // namespace field

} // namespace ublox


