// Generated by commsdsl2comms v3.6.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::field::InfMask field.

#pragma once

#include <type_traits>

namespace ublox
{

namespace field
{

/// @brief Common functions for
///     @ref ublox::field::InfMask field.
struct InfMaskCommon
{
    /// @brief Name of the @ref ublox::field::InfMask field.
    static const char* name()
    {
        return "InfMask";
    }
    
    /// @brief Retrieve name of the bit of
    ///     @ref ublox::field::InfMask field.
    static const char* bitName(std::size_t idx)
    {
        static const char* Map[] = {
            "ERROR",
            "WARNING",
            "NOTICE",
            "TEST",
            "DEBUG"
        };
    
        static const std::size_t MapSize = std::extent<decltype(Map)>::value;
        if (MapSize <= idx) {
            return nullptr;
        }
    
        return Map[idx];
    }
    
};

} // namespace field

} // namespace ublox


