// Generated by commsdsl2comms v3.6.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::field::PsmState field.

#pragma once

#include <cstdint>
#include <type_traits>

namespace ublox
{

namespace field
{

/// @brief Common types and functions for
///     @ref ublox::field::PsmState field.
struct PsmStateCommon
{
    /// @brief Values enumerator for
    ///     @ref ublox::field::PsmState field.
    enum class ValueType : std::uint8_t
    {
        NotAvailable = 0, ///< value <b>N/A</b>.
        Enabled = 1, ///< value <b>ENABLED</b>.
        Acquisition = 2, ///< value <b>ACQUISITION</b>.
        Tracking = 3, ///< value <b>TRACKING</b>.
        PowerOptTracking = 4, ///< value <b>POWER OPTIMIZED TRACKING</b>.
        Inactive = 5, ///< value <b>INACTIVE</b>.
        
        // --- Extra values generated for convenience ---
        FirstValue = 0, ///< First defined value.
        LastValue = 5, ///< Last defined value.
        ValuesLimit = 6, ///< Upper limit for defined values.
        
    };
    
    /// @brief Name of the @ref ublox::field::PsmState field.
    static const char* name()
    {
        return "psmState";
    }
    
    /// @brief Retrieve name of the enum value
    static const char* valueName(ValueType val)
    {
        static const char* Map[] = {
            "N/A",
            "ENABLED",
            "ACQUISITION",
            "TRACKING",
            "POWER OPTIMIZED TRACKING",
            "INACTIVE"
        };
        static const std::size_t MapSize = std::extent<decltype(Map)>::value;
        
        if (MapSize <= static_cast<std::size_t>(val)) {
            return nullptr;
        }
        
        return Map[static_cast<std::size_t>(val)];
    }
    
};

/// @brief Values enumerator for
///     @ref ublox::field::PsmState field.
using PsmStateVal = PsmStateCommon::ValueType;

} // namespace field

} // namespace ublox


