// Generated by commsdsl2comms v6.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_ublox::field::CfgValR8 field.

#pragma once

namespace cc_ublox
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_ublox::field::CfgValR8 field.
struct CfgValR8Common
{
    /// @brief Re-definition of the value type used by
    ///     cc_ublox::field::CfgValR8 field.
    using ValueType = double;

    /// @brief Name of the @ref cc_ublox::field::CfgValR8 field.
    static const char* name()
    {
        return "Val";
    }

    /// @brief Compile time detection of special values presence.
    static constexpr bool hasSpecials()
    {
        return false;
    }
};

} // namespace field

} // namespace cc_ublox
