// Generated by commsdsl2comms v3.6.4

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::CfgOdoPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::CfgOdoPoll message.
/// @see ublox::message::CfgOdoPoll
struct CfgOdoPollCommon
{
    /// @brief Name of the @ref ublox::message::CfgOdoPoll message.
    static const char* name()
    {
        return "CFG-ODO (Poll)";
    }
    
};

} // namespace message

} // namespace ublox


