// Generated by commsdsl2comms v3.6.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::CfgPrtPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::CfgPrtPoll message.
/// @see ublox::message::CfgPrtPoll
struct CfgPrtPollCommon
{
    /// @brief Name of the @ref ublox::message::CfgPrtPoll message.
    static const char* name()
    {
        return "CFG-PRT (Poll)";
    }
    
};

} // namespace message

} // namespace ublox


