// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::NavPosllhPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::NavPosllhPoll message.
struct NavPosllhPollCommon
{
    /// @brief Name of the @ref ublox::message::NavPosllhPoll message.
    static const char* name()
    {
        return "NAV-POSLLH (Poll)";
    }
};

} // namespace message

} // namespace ublox
