// Generated by commsdsl2comms v3.5.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::NavPosecefPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::NavPosecefPoll message.
/// @see ublox::message::NavPosecefPoll
struct NavPosecefPollCommon
{
    /// @brief Name of the @ref ublox::message::NavPosecefPoll message.
    static const char* name()
    {
        return "NAV-POSECEF (Poll)";
    }
    
};

} // namespace message

} // namespace ublox


