// Generated by commsdsl2comms v3.6.4

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::NavSatPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::NavSatPoll message.
/// @see ublox::message::NavSatPoll
struct NavSatPollCommon
{
    /// @brief Name of the @ref ublox::message::NavSatPoll message.
    static const char* name()
    {
        return "NAV-SAT (Poll)";
    }
    
};

} // namespace message

} // namespace ublox


