// Generated by commsdsl2comms v3.3.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::RxmAlmPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::RxmAlmPoll message.
/// @see ublox::message::RxmAlmPoll
struct RxmAlmPollCommon
{
    /// @brief Name of the @ref ublox::message::RxmAlmPoll message.
    static const char* name()
    {
        return "RXM-ALM (Poll)";
    }
    
};

} // namespace message

} // namespace ublox


