// Generated by commsdsl2comms v3.7.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::SecUniqid message and its fields.

#pragma once

#include <cstdint>
#include <type_traits>
#include <utility>
#include "ublox/field/Res3Common.h"

namespace ublox
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref ublox::message::SecUniqid message.
/// @see ublox::message::SecUniqidFields
struct SecUniqidFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref ublox::message::SecUniqidFields::Version field.
    struct VersionCommon
    {
        /// @brief Re-definition of the value type used by
        ///     ublox::message::SecUniqidFields::Version field.
        using ValueType = std::uint8_t;
    
        /// @brief Name of the @ref ublox::message::SecUniqidFields::Version field.
        static const char* name()
        {
            return "version";
        }
        
        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
        
    };
    
    /// @brief Common types and functions for
    ///     @ref ublox::message::SecUniqidFields::Reserved1 field.
    struct Reserved1Common : public ublox::field::Res3Common
    {
        /// @brief Name of the @ref ublox::message::SecUniqidFields::Reserved1 field.
        static const char* name()
        {
            return "reserved1";
        }
        
    };
    
    /// @brief Scope for all the common definitions of the
    ///     @ref ublox::message::SecUniqidFields::UniqueId field.
    struct UniqueIdCommon
    {
        /// @brief Name of the @ref ublox::message::SecUniqidFields::UniqueId field.
        static const char* name()
        {
            return "uniqueId";
        }
        
    };
    
    
};

/// @brief Common types and functions of 
///     @ref ublox::message::SecUniqid message.
/// @see ublox::message::SecUniqid
struct SecUniqidCommon
{
    /// @brief Name of the @ref ublox::message::SecUniqid message.
    static const char* name()
    {
        return "SEC-UNIQID";
    }
    
};

} // namespace message

} // namespace ublox


