// Generated by commsdsl2comms v3.5.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::TimFchgPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref ublox::message::TimFchgPoll message.
/// @see ublox::message::TimFchgPoll
struct TimFchgPollCommon
{
    /// @brief Name of the @ref ublox::message::TimFchgPoll message.
    static const char* name()
    {
        return "TIM-FCHG (Poll)";
    }
    
};

} // namespace message

} // namespace ublox


