// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref ublox::message::TimTpPoll message and its fields.

#pragma once

namespace ublox
{

namespace message
{


/// @brief Common types and functions of 
///     @ref ublox::message::TimTpPoll message.
struct TimTpPollCommon
{
    /// @brief Name of the @ref ublox::message::TimTpPoll message.
    static const char* name()
    {
        return "TIM-TP (Poll)";
    }
    
};

} // namespace message

} // namespace ublox



