// Generated by commsdsl2comms v6.3.4

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_ublox::message::AidAopPoll message and its fields.

#pragma once

namespace cc_ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_ublox::message::AidAopPoll message.
struct AidAopPollCommon
{
    /// @brief Name of the @ref cc_ublox::message::AidAopPoll message.
    static const char* name()
    {
        return "AID-AOP (Poll)";
    }
};

} // namespace message

} // namespace cc_ublox
