// Generated by commsdsl2comms v6.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_ublox::message::CfgEsrcPoll message and its fields.

#pragma once

namespace cc_ublox
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_ublox::message::CfgEsrcPoll message.
struct CfgEsrcPollCommon
{
    /// @brief Name of the @ref cc_ublox::message::CfgEsrcPoll message.
    static const char* name()
    {
        return "CFG-ESRC (Poll)";
    }
};

} // namespace message

} // namespace cc_ublox
