// Generated by commsdsl2comms v6.2.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_ublox::message::MgaBdsHealth message and its fields.

#pragma once

#include <cstdint>
#include "cc_ublox/field/Res2Common.h"
#include "cc_ublox/field/Res4Common.h"

namespace cc_ublox
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_ublox::message::MgaBdsHealth message.
/// @see cc_ublox::message::MgaBdsHealthFields
struct MgaBdsHealthFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaBdsHealthFields::Type field.
    struct TypeCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaBdsHealthFields::Type field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaBdsHealthFields::Type field.
        static const char* name()
        {
            return "type";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaBdsHealthFields::Version field.
    struct VersionCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaBdsHealthFields::Version field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaBdsHealthFields::Version field.
        static const char* name()
        {
            return "version";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaBdsHealthFields::Reserved1 field.
    struct Reserved1Common : public cc_ublox::field::Res2Common
    {
        /// @brief Name of the @ref cc_ublox::message::MgaBdsHealthFields::Reserved1 field.
        static const char* name()
        {
            return "reserved1";
        }
    };

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref cc_ublox::message::MgaBdsHealthFields::HealthCode field.
    struct HealthCodeMembersCommon
    {
        /// @brief Common types and functions for
        ///     @ref cc_ublox::message::MgaBdsHealthFields::HealthCodeMembers::Element field.
        struct ElementCommon
        {
            /// @brief Re-definition of the value type used by
            ///     cc_ublox::message::MgaBdsHealthFields::HealthCodeMembers::Element field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref cc_ublox::message::MgaBdsHealthFields::HealthCodeMembers::Element field.
            static const char* name()
            {
                return "";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaBdsHealthFields::HealthCode field.
    struct HealthCodeCommon
    {
        /// @brief Name of the @ref cc_ublox::message::MgaBdsHealthFields::HealthCode field.
        static const char* name()
        {
            return "healthCode";
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaBdsHealthFields::Reserved2 field.
    struct Reserved2Common : public cc_ublox::field::Res4Common
    {
        /// @brief Name of the @ref cc_ublox::message::MgaBdsHealthFields::Reserved2 field.
        static const char* name()
        {
            return "reserved2";
        }
    };
};

/// @brief Common types and functions of 
///     @ref cc_ublox::message::MgaBdsHealth message.
struct MgaBdsHealthCommon
{
    /// @brief Name of the @ref cc_ublox::message::MgaBdsHealth message.
    static const char* name()
    {
        return "MGA-BDS-HEALTH";
    }
};

} // namespace message

} // namespace cc_ublox
