// Generated by commsdsl2comms v7.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_ublox::message::MgaGpsIono message and its fields.

#pragma once

#include <cstdint>
#include "cc_ublox/field/Res2Common.h"
#include "cc_ublox/field/Res4Common.h"

namespace cc_ublox
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_ublox::message::MgaGpsIono message.
/// @see cc_ublox::message::MgaGpsIonoFields
struct MgaGpsIonoFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::Type field.
    struct TypeCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::Type field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::Type field.
        static const char* name()
        {
            return "type";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::Version field.
    struct VersionCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::Version field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::Version field.
        static const char* name()
        {
            return "version";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::Reserved1 field.
    struct Reserved1Common : public cc_ublox::field::Res2Common
    {
        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::Reserved1 field.
        static const char* name()
        {
            return "reserved1";
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha0 field.
    struct IonoAlpha0Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoAlpha0 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha0 field.
        static const char* name()
        {
            return "ionoAlpha0";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha1 field.
    struct IonoAlpha1Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoAlpha1 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha1 field.
        static const char* name()
        {
            return "ionoAlpha1";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha2 field.
    struct IonoAlpha2Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoAlpha2 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha2 field.
        static const char* name()
        {
            return "ionoAlpha2";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha3 field.
    struct IonoAlpha3Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoAlpha3 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoAlpha3 field.
        static const char* name()
        {
            return "ionoAlpha3";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta0 field.
    struct IonoBeta0Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoBeta0 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta0 field.
        static const char* name()
        {
            return "ionoBeta0";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta1 field.
    struct IonoBeta1Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoBeta1 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta1 field.
        static const char* name()
        {
            return "ionoBeta1";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta2 field.
    struct IonoBeta2Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoBeta2 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta2 field.
        static const char* name()
        {
            return "ionoBeta2";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta3 field.
    struct IonoBeta3Common
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::MgaGpsIonoFields::IonoBeta3 field.
        using ValueType = std::int8_t;

        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::IonoBeta3 field.
        static const char* name()
        {
            return "ionoBeta3";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::MgaGpsIonoFields::Reserved2 field.
    struct Reserved2Common : public cc_ublox::field::Res4Common
    {
        /// @brief Name of the @ref cc_ublox::message::MgaGpsIonoFields::Reserved2 field.
        static const char* name()
        {
            return "reserved2";
        }
    };
};

/// @brief Common types and functions of 
///     @ref cc_ublox::message::MgaGpsIono message.
struct MgaGpsIonoCommon
{
    /// @brief Name of the @ref cc_ublox::message::MgaGpsIono message.
    static const char* name()
    {
        return "MGA-GPS-IONO";
    }
};

} // namespace message

} // namespace cc_ublox
