// Generated by commsdsl2comms v7.0.0

/// @file
/// @brief Contains definition of <b>"NAV-PVT"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "cc_ublox/MsgId.h"
#include "cc_ublox/field/Day.h"
#include "cc_ublox/field/Dop.h"
#include "cc_ublox/field/FieldBase.h"
#include "cc_ublox/field/GpsFix.h"
#include "cc_ublox/field/HAcc.h"
#include "cc_ublox/field/HMSL.h"
#include "cc_ublox/field/Heading.h"
#include "cc_ublox/field/HeadingAcc.h"
#include "cc_ublox/field/Height.h"
#include "cc_ublox/field/Hour.h"
#include "cc_ublox/field/Itow.h"
#include "cc_ublox/field/Lat.h"
#include "cc_ublox/field/Lon.h"
#include "cc_ublox/field/Min.h"
#include "cc_ublox/field/Month.h"
#include "cc_ublox/field/PsmState.h"
#include "cc_ublox/field/Res1.h"
#include "cc_ublox/field/Res4.h"
#include "cc_ublox/field/Sec.h"
#include "cc_ublox/field/VAcc.h"
#include "cc_ublox/field/Vel.h"
#include "cc_ublox/field/Year.h"
#include "cc_ublox/message/NavPvtCommon.h"
#include "cc_ublox/options/DefaultOptions.h"
#include "comms/MessageBase.h"
#include "comms/field/Bitfield.h"
#include "comms/field/BitmaskValue.h"
#include "comms/field/EnumValue.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace cc_ublox
{

namespace message
{

/// @brief Fields of @ref NavPvt.
/// @tparam TOpt Extra options
/// @see @ref NavPvt
/// @headerfile cc_ublox/message/NavPvt.h
template <typename TOpt = cc_ublox::options::DefaultOptions>
struct NavPvtFields
{
    /// @brief Definition of <b>"iTOW"</b> field.
    using Itow =
        cc_ublox::field::Itow<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"year"</b> field.
    using Year =
        cc_ublox::field::Year<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"month"</b> field.
    using Month =
        cc_ublox::field::Month<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"day"</b> field.
    using Day =
        cc_ublox::field::Day<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"hour"</b> field.
    using Hour =
        cc_ublox::field::Hour<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"min"</b> field.
    using Min =
        cc_ublox::field::Min<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"sec"</b> field.
    using Sec =
        cc_ublox::field::Sec<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"valid"</b> field.
    class Valid : public
        comms::field::BitmaskValue<
            cc_ublox::field::FieldBase<>,
            comms::option::def::HasName,
            comms::option::def::FixedLength<1U>,
            comms::option::def::BitmaskReservedBits<0xF0U, 0x0U>
        >
    {
        using Base =
            comms::field::BitmaskValue<
                cc_ublox::field::FieldBase<>,
                comms::option::def::HasName,
                comms::option::def::FixedLength<1U>,
                comms::option::def::BitmaskReservedBits<0xF0U, 0x0U>
            >;
    public:
        /// @brief Provides names and generates access functions for internal bits.
        /// @details See definition of @b COMMS_BITMASK_BITS_SEQ macro
        ///     related to @b comms::field::BitmaskValue class from COMMS library
        ///     for details.
        ///
        ///      The generated enum values and functions are:
        ///      @li @b BitIdx_validDate, @b getBitValue_validDate() and @b setBitValue_validDate().
        ///      @li @b BitIdx_validTime, @b getBitValue_validTime() and @b setBitValue_validTime().
        ///      @li @b BitIdx_fullyResolved, @b getBitValue_fullyResolved() and @b setBitValue_fullyResolved().
        ///      @li @b BitIdx_validMag, @b getBitValue_validMag() and @b setBitValue_validMag().
        COMMS_BITMASK_BITS_SEQ(
            validDate,
            validTime,
            fullyResolved,
            validMag
        );

        /// @brief Retrieve name of the bit.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::ValidCommon::bitName().
        static const char* bitName(std::size_t idx)
        {
            return cc_ublox::message::NavPvtFieldsCommon::ValidCommon::bitName(idx);
        }

        /// @brief Retrieve name of the bit.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::ValidCommon::bitName().
        static const char* bitName(BitIdx idx)
        {
            return bitName(static_cast<std::size_t>(idx));
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::ValidCommon::name();
        }
    };

    /// @brief Definition of <b>"tAcc"</b> field.
    class TAcc : public
        comms::field::IntValue<
            cc_ublox::field::FieldBase<>,
            std::uint32_t,
            comms::option::def::HasName,
            comms::option::def::UnitsNanoseconds
        >
    {
        using Base =
            comms::field::IntValue<
                cc_ublox::field::FieldBase<>,
                std::uint32_t,
                comms::option::def::HasName,
                comms::option::def::UnitsNanoseconds
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_ublox::message::NavPvtFieldsCommon::TAccCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::TAccCommon::name();
        }
    };

    /// @brief Definition of <b>"nano"</b> field.
    class Nano : public
        comms::field::IntValue<
            cc_ublox::field::FieldBase<>,
            std::int32_t,
            comms::option::def::HasName,
            comms::option::def::UnitsNanoseconds
        >
    {
        using Base =
            comms::field::IntValue<
                cc_ublox::field::FieldBase<>,
                std::int32_t,
                comms::option::def::HasName,
                comms::option::def::UnitsNanoseconds
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_ublox::message::NavPvtFieldsCommon::NanoCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::NanoCommon::name();
        }
    };

    /// @brief Definition of <b>"fixType"</b> field.
    class FixType : public
        cc_ublox::field::GpsFix<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::GpsFix<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::FixTypeCommon::name();
        }
    };

    /// @brief Scope for all the member fields of
    ///     @ref Flags field.
    struct FlagsMembers
    {
        /// @brief Definition of <b>""</b> field.
        class LowBits : public
            comms::field::BitmaskValue<
                cc_ublox::field::FieldBase<>,
                comms::option::def::HasName,
                comms::option::def::FixedBitLength<2U>
            >
        {
            using Base =
                comms::field::BitmaskValue<
                    cc_ublox::field::FieldBase<>,
                    comms::option::def::HasName,
                    comms::option::def::FixedBitLength<2U>
                >;
        public:
            /// @brief Provides names and generates access functions for internal bits.
            /// @details See definition of @b COMMS_BITMASK_BITS_SEQ macro
            ///     related to @b comms::field::BitmaskValue class from COMMS library
            ///     for details.
            ///
            ///      The generated enum values and functions are:
            ///      @li @b BitIdx_gnssFixOK, @b getBitValue_gnssFixOK() and @b setBitValue_gnssFixOK().
            ///      @li @b BitIdx_diffSoln, @b getBitValue_diffSoln() and @b setBitValue_diffSoln().
            COMMS_BITMASK_BITS_SEQ(
                gnssFixOK,
                diffSoln
            );

            /// @brief Retrieve name of the bit.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::LowBitsCommon::bitName().
            static const char* bitName(std::size_t idx)
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::LowBitsCommon::bitName(idx);
            }

            /// @brief Retrieve name of the bit.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::LowBitsCommon::bitName().
            static const char* bitName(BitIdx idx)
            {
                return bitName(static_cast<std::size_t>(idx));
            }

            /// @brief Name of the field.
            static const char* name()
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::LowBitsCommon::name();
            }
        };

        /// @brief Definition of <b>"psmState"</b> field.
        using PsmState =
            cc_ublox::field::PsmState<
                TOpt,
                comms::option::def::HasName,
                comms::option::def::FixedBitLength<3U>
            >;

        /// @brief Definition of <b>""</b> field.
        class MidBits : public
            comms::field::BitmaskValue<
                cc_ublox::field::FieldBase<>,
                comms::option::def::HasName,
                comms::option::def::FixedBitLength<1U>
            >
        {
            using Base =
                comms::field::BitmaskValue<
                    cc_ublox::field::FieldBase<>,
                    comms::option::def::HasName,
                    comms::option::def::FixedBitLength<1U>
                >;
        public:
            /// @brief Provides names and generates access functions for internal bits.
            /// @details See definition of @b COMMS_BITMASK_BITS_SEQ macro
            ///     related to @b comms::field::BitmaskValue class from COMMS library
            ///     for details.
            ///
            ///      The generated enum values and functions are:
            ///      @li @b BitIdx_headVehValid, @b getBitValue_headVehValid() and @b setBitValue_headVehValid().
            COMMS_BITMASK_BITS_SEQ(
                headVehValid
            );

            /// @brief Retrieve name of the bit.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::MidBitsCommon::bitName().
            static const char* bitName(std::size_t idx)
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::MidBitsCommon::bitName(idx);
            }

            /// @brief Retrieve name of the bit.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::MidBitsCommon::bitName().
            static const char* bitName(BitIdx idx)
            {
                return bitName(static_cast<std::size_t>(idx));
            }

            /// @brief Name of the field.
            static const char* name()
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::MidBitsCommon::name();
            }
        };

        /// @brief Definition of <b>"carrSoln"</b> field.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::ValueType
        class CarrSoln : public
            comms::field::EnumValue<
                cc_ublox::field::FieldBase<>,
                cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::ValueType,
                comms::option::def::HasName,
                comms::option::def::FixedBitLength<2U>,
                comms::option::def::ValidNumValueRange<0, 2>
            >
        {
            using Base =
                comms::field::EnumValue<
                    cc_ublox::field::FieldBase<>,
                    cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::ValueType,
                    comms::option::def::HasName,
                    comms::option::def::FixedBitLength<2U>,
                    comms::option::def::ValidNumValueRange<0, 2>
                >;
        public:
            /// @brief Re-definition of the value type.
            using ValueType = typename Base::ValueType;

            /// @brief Single value name info entry.
            using ValueNameInfo = cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::ValueNameInfo;

            /// @brief Type returned from @ref valueNamesMap() member function.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::ValueNamesMapInfo.
            using ValueNamesMapInfo = cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::ValueNamesMapInfo;

            /// @brief Retrieve name of the enum value.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::valueName().
            static const char* valueName(ValueType val)
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::valueName(val);
            }

            /// @brief Retrieve name of the enum value.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::valueName().
            static const char* valueNameOf(ValueType val)
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::valueName(val);
            }

            /// @brief Retrieve name of the @b current value
            const char* valueName() const
            {
                return valueName(Base::getValue());
            }

            /// @brief Retrieve map of enum value names.
            /// @see @ref cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::valueNamesMap().
            static ValueNamesMapInfo valueNamesMap()
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::valueNamesMap();
            }

            /// @brief Name of the field.
            static const char* name()
            {
                return cc_ublox::message::NavPvtFieldsCommon::FlagsMembersCommon::CarrSolnCommon::name();
            }
        };

        /// @brief All members bundled in @b std::tuple.
        using All =
            std::tuple<
               LowBits,
               PsmState,
               MidBits,
               CarrSoln
            >;
    };

    /// @brief Definition of <b>"flags"</b> field.
    class Flags : public
        comms::field::Bitfield<
            cc_ublox::field::FieldBase<>,
            typename FlagsMembers::All,
            comms::option::def::HasName,
            comms::option::def::HasVersionDependentMembers<false>
        >
    {
        using Base =
            comms::field::Bitfield<
                cc_ublox::field::FieldBase<>,
                typename FlagsMembers::All,
                comms::option::def::HasName,
                comms::option::def::HasVersionDependentMembers<false>
            >;
    public:
        /// @brief Allow access to internal fields.
        /// @details See definition of @b COMMS_FIELD_MEMBERS_NAMES macro
        ///     related to @b comms::field::Bitfield class from COMMS library
        ///     for details.
        ///
        ///     The generated values, types and access functions are:
        ///     @li @b FieldIdx_lowBits index, @b Field_lowBits type and @b field_lowBits() access function -
        ///         for cc_ublox::message::NavPvtFields::FlagsMembers::LowBits member field.
        ///     @li @b FieldIdx_psmState index, @b Field_psmState type and @b field_psmState() access function -
        ///         for cc_ublox::message::NavPvtFields::FlagsMembers::PsmState member field.
        ///     @li @b FieldIdx_midBits index, @b Field_midBits type and @b field_midBits() access function -
        ///         for cc_ublox::message::NavPvtFields::FlagsMembers::MidBits member field.
        ///     @li @b FieldIdx_carrSoln index, @b Field_carrSoln type and @b field_carrSoln() access function -
        ///         for cc_ublox::message::NavPvtFields::FlagsMembers::CarrSoln member field.
        COMMS_FIELD_MEMBERS_NAMES(
            lowBits,
            psmState,
            midBits,
            carrSoln
        );

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::FlagsCommon::name();
        }
    };

    /// @brief Definition of <b>"flags2"</b> field.
    class Flags2 : public
        comms::field::BitmaskValue<
            cc_ublox::field::FieldBase<>,
            comms::option::def::HasName,
            comms::option::def::FixedLength<1U>,
            comms::option::def::BitmaskReservedBits<0x1FU, 0x0U>
        >
    {
        using Base =
            comms::field::BitmaskValue<
                cc_ublox::field::FieldBase<>,
                comms::option::def::HasName,
                comms::option::def::FixedLength<1U>,
                comms::option::def::BitmaskReservedBits<0x1FU, 0x0U>
            >;
    public:
        /// @brief Provide names for internal bits.
        /// @details See definition of @b COMMS_BITMASK_BITS macro
        ///     related to @b comms::field::BitmaskValue class from COMMS library
        ///     for details.
        ///
        ///      The generated enum values:
        ///      @li @b BitIdx_confirmedAvai.
        ///      @li @b BitIdx_confirmedDate.
        ///      @li @b BitIdx_confirmedTime.
        COMMS_BITMASK_BITS(
            confirmedAvai=5,
            confirmedDate=6,
            confirmedTime=7
        );

        /// @brief Generates independent access functions for internal bits.
        /// @details See definition of @b COMMS_BITMASK_BITS_ACCESS macro
        ///     related to @b comms::field::BitmaskValue class from COMMS library
        ///     for details.
        ///
        ///     The generated access functions are:
        ///      @li @b getBitValue_confirmedAvai() and @b setBitValue_confirmedAvai().
        ///      @li @b getBitValue_confirmedDate() and @b setBitValue_confirmedDate().
        ///      @li @b getBitValue_confirmedTime() and @b setBitValue_confirmedTime().
        COMMS_BITMASK_BITS_ACCESS(
            confirmedAvai,
            confirmedDate,
            confirmedTime
        );

        /// @brief Retrieve name of the bit.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::Flags2Common::bitName().
        static const char* bitName(std::size_t idx)
        {
            return cc_ublox::message::NavPvtFieldsCommon::Flags2Common::bitName(idx);
        }

        /// @brief Retrieve name of the bit.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::Flags2Common::bitName().
        static const char* bitName(BitIdx idx)
        {
            return bitName(static_cast<std::size_t>(idx));
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::Flags2Common::name();
        }
    };

    /// @brief Definition of <b>"numSV"</b> field.
    class NumSV : public
        comms::field::IntValue<
            cc_ublox::field::FieldBase<>,
            std::uint8_t,
            comms::option::def::HasName
        >
    {
        using Base =
            comms::field::IntValue<
                cc_ublox::field::FieldBase<>,
                std::uint8_t,
                comms::option::def::HasName
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_ublox::message::NavPvtFieldsCommon::NumSVCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::NumSVCommon::name();
        }
    };

    /// @brief Definition of <b>"lon"</b> field.
    using Lon =
        cc_ublox::field::Lon<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"lat"</b> field.
    using Lat =
        cc_ublox::field::Lat<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"height"</b> field.
    using Height =
        cc_ublox::field::Height<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"hMSL"</b> field.
    using HMSL =
        cc_ublox::field::HMSL<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"hAcc"</b> field.
    using HAcc =
        cc_ublox::field::HAcc<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"vAcc"</b> field.
    using VAcc =
        cc_ublox::field::VAcc<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"velN"</b> field.
    class VelN : public
        cc_ublox::field::Vel<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Vel<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::VelNCommon::name();
        }
    };

    /// @brief Definition of <b>"velE"</b> field.
    class VelE : public
        cc_ublox::field::Vel<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Vel<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::VelECommon::name();
        }
    };

    /// @brief Definition of <b>"velD"</b> field.
    class VelD : public
        cc_ublox::field::Vel<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Vel<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::VelDCommon::name();
        }
    };

    /// @brief Definition of <b>"gSpeed"</b> field.
    class GSpeed : public
        cc_ublox::field::Vel<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Vel<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::GSpeedCommon::name();
        }
    };

    /// @brief Definition of <b>"heading"</b> field.
    using Heading =
        cc_ublox::field::Heading<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"sAcc"</b> field.
    class SAcc : public
        comms::field::IntValue<
            cc_ublox::field::FieldBase<>,
            std::uint32_t,
            comms::option::def::HasName,
            comms::option::def::UnitsMillimetersPerSecond
        >
    {
        using Base =
            comms::field::IntValue<
                cc_ublox::field::FieldBase<>,
                std::uint32_t,
                comms::option::def::HasName,
                comms::option::def::UnitsMillimetersPerSecond
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_ublox::message::NavPvtFieldsCommon::SAccCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::SAccCommon::name();
        }
    };

    /// @brief Definition of <b>"headingAcc"</b> field.
    using HeadingAcc =
        cc_ublox::field::HeadingAcc<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Definition of <b>"pDop"</b> field.
    class PDop : public
        cc_ublox::field::Dop<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Dop<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::PDopCommon::name();
        }
    };

    /// @brief Definition of <b>"flags3"</b> field.
    class Flags3 : public
        comms::field::BitmaskValue<
            cc_ublox::field::FieldBase<>,
            comms::option::def::HasName,
            comms::option::def::FixedLength<1U>,
            comms::option::def::BitmaskReservedBits<0xFEU, 0x0U>
        >
    {
        using Base =
            comms::field::BitmaskValue<
                cc_ublox::field::FieldBase<>,
                comms::option::def::HasName,
                comms::option::def::FixedLength<1U>,
                comms::option::def::BitmaskReservedBits<0xFEU, 0x0U>
            >;
    public:
        /// @brief Provides names and generates access functions for internal bits.
        /// @details See definition of @b COMMS_BITMASK_BITS_SEQ macro
        ///     related to @b comms::field::BitmaskValue class from COMMS library
        ///     for details.
        ///
        ///      The generated enum values and functions are:
        ///      @li @b BitIdx_invalidLlh, @b getBitValue_invalidLlh() and @b setBitValue_invalidLlh().
        COMMS_BITMASK_BITS_SEQ(
            invalidLlh
        );

        /// @brief Retrieve name of the bit.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::Flags3Common::bitName().
        static const char* bitName(std::size_t idx)
        {
            return cc_ublox::message::NavPvtFieldsCommon::Flags3Common::bitName(idx);
        }

        /// @brief Retrieve name of the bit.
        /// @see @ref cc_ublox::message::NavPvtFieldsCommon::Flags3Common::bitName().
        static const char* bitName(BitIdx idx)
        {
            return bitName(static_cast<std::size_t>(idx));
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::Flags3Common::name();
        }
    };

    /// @brief Definition of <b>"reserved2"</b> field.
    class Reserved2 : public
        cc_ublox::field::Res1<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Res1<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::Reserved2Common::name();
        }
    };

    /// @brief Definition of <b>"reserved3"</b> field.
    class Reserved3 : public
        cc_ublox::field::Res4<
            TOpt,
            comms::option::def::HasName
        >
    {
        using Base =
            cc_ublox::field::Res4<
                TOpt,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::NavPvtFieldsCommon::Reserved3Common::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Itow,
        Year,
        Month,
        Day,
        Hour,
        Min,
        Sec,
        Valid,
        TAcc,
        Nano,
        FixType,
        Flags,
        Flags2,
        NumSV,
        Lon,
        Lat,
        Height,
        HMSL,
        HAcc,
        VAcc,
        VelN,
        VelE,
        VelD,
        GSpeed,
        Heading,
        SAcc,
        HeadingAcc,
        PDop,
        Flags3,
        Reserved2,
        Reserved3
    >;
};

/// @brief Definition of <b>"NAV-PVT"</b> message class.
/// @details
///     See @ref NavPvtFields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile cc_ublox/message/NavPvt.h
template <typename TMsgBase, typename TOpt = cc_ublox::options::DefaultOptions>
class NavPvt : public
    comms::MessageBase<
        TMsgBase,
        typename TOpt::message::NavPvt,
        comms::option::def::StaticNumIdImpl<cc_ublox::MsgId_NavPvt>,
        comms::option::def::FieldsImpl<typename NavPvtFields<TOpt>::All>,
        comms::option::def::MsgType<NavPvt<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            typename TOpt::message::NavPvt,
            comms::option::def::StaticNumIdImpl<cc_ublox::MsgId_NavPvt>,
            comms::option::def::FieldsImpl<typename NavPvtFields<TOpt>::All>,
            comms::option::def::MsgType<NavPvt<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_itow index, @b Field_itow type and @b field_itow() access fuction
    ///         for @ref NavPvtFields::Itow field.
    ///     @li @b FieldIdx_year index, @b Field_year type and @b field_year() access fuction
    ///         for @ref NavPvtFields::Year field.
    ///     @li @b FieldIdx_month index, @b Field_month type and @b field_month() access fuction
    ///         for @ref NavPvtFields::Month field.
    ///     @li @b FieldIdx_day index, @b Field_day type and @b field_day() access fuction
    ///         for @ref NavPvtFields::Day field.
    ///     @li @b FieldIdx_hour index, @b Field_hour type and @b field_hour() access fuction
    ///         for @ref NavPvtFields::Hour field.
    ///     @li @b FieldIdx_min index, @b Field_min type and @b field_min() access fuction
    ///         for @ref NavPvtFields::Min field.
    ///     @li @b FieldIdx_sec index, @b Field_sec type and @b field_sec() access fuction
    ///         for @ref NavPvtFields::Sec field.
    ///     @li @b FieldIdx_valid index, @b Field_valid type and @b field_valid() access fuction
    ///         for @ref NavPvtFields::Valid field.
    ///     @li @b FieldIdx_tAcc index, @b Field_tAcc type and @b field_tAcc() access fuction
    ///         for @ref NavPvtFields::TAcc field.
    ///     @li @b FieldIdx_nano index, @b Field_nano type and @b field_nano() access fuction
    ///         for @ref NavPvtFields::Nano field.
    ///     @li @b FieldIdx_fixType index, @b Field_fixType type and @b field_fixType() access fuction
    ///         for @ref NavPvtFields::FixType field.
    ///     @li @b FieldIdx_flags index, @b Field_flags type and @b field_flags() access fuction
    ///         for @ref NavPvtFields::Flags field.
    ///     @li @b FieldIdx_flags2 index, @b Field_flags2 type and @b field_flags2() access fuction
    ///         for @ref NavPvtFields::Flags2 field.
    ///     @li @b FieldIdx_numSV index, @b Field_numSV type and @b field_numSV() access fuction
    ///         for @ref NavPvtFields::NumSV field.
    ///     @li @b FieldIdx_lon index, @b Field_lon type and @b field_lon() access fuction
    ///         for @ref NavPvtFields::Lon field.
    ///     @li @b FieldIdx_lat index, @b Field_lat type and @b field_lat() access fuction
    ///         for @ref NavPvtFields::Lat field.
    ///     @li @b FieldIdx_height index, @b Field_height type and @b field_height() access fuction
    ///         for @ref NavPvtFields::Height field.
    ///     @li @b FieldIdx_hMSL index, @b Field_hMSL type and @b field_hMSL() access fuction
    ///         for @ref NavPvtFields::HMSL field.
    ///     @li @b FieldIdx_hAcc index, @b Field_hAcc type and @b field_hAcc() access fuction
    ///         for @ref NavPvtFields::HAcc field.
    ///     @li @b FieldIdx_vAcc index, @b Field_vAcc type and @b field_vAcc() access fuction
    ///         for @ref NavPvtFields::VAcc field.
    ///     @li @b FieldIdx_velN index, @b Field_velN type and @b field_velN() access fuction
    ///         for @ref NavPvtFields::VelN field.
    ///     @li @b FieldIdx_velE index, @b Field_velE type and @b field_velE() access fuction
    ///         for @ref NavPvtFields::VelE field.
    ///     @li @b FieldIdx_velD index, @b Field_velD type and @b field_velD() access fuction
    ///         for @ref NavPvtFields::VelD field.
    ///     @li @b FieldIdx_gSpeed index, @b Field_gSpeed type and @b field_gSpeed() access fuction
    ///         for @ref NavPvtFields::GSpeed field.
    ///     @li @b FieldIdx_heading index, @b Field_heading type and @b field_heading() access fuction
    ///         for @ref NavPvtFields::Heading field.
    ///     @li @b FieldIdx_sAcc index, @b Field_sAcc type and @b field_sAcc() access fuction
    ///         for @ref NavPvtFields::SAcc field.
    ///     @li @b FieldIdx_headingAcc index, @b Field_headingAcc type and @b field_headingAcc() access fuction
    ///         for @ref NavPvtFields::HeadingAcc field.
    ///     @li @b FieldIdx_pDop index, @b Field_pDop type and @b field_pDop() access fuction
    ///         for @ref NavPvtFields::PDop field.
    ///     @li @b FieldIdx_flags3 index, @b Field_flags3 type and @b field_flags3() access fuction
    ///         for @ref NavPvtFields::Flags3 field.
    ///     @li @b FieldIdx_reserved2 index, @b Field_reserved2 type and @b field_reserved2() access fuction
    ///         for @ref NavPvtFields::Reserved2 field.
    ///     @li @b FieldIdx_reserved3 index, @b Field_reserved3 type and @b field_reserved3() access fuction
    ///         for @ref NavPvtFields::Reserved3 field.
    COMMS_MSG_FIELDS_NAMES(
        itow,
        year,
        month,
        day,
        hour,
        min,
        sec,
        valid,
        tAcc,
        nano,
        fixType,
        flags,
        flags2,
        numSV,
        lon,
        lat,
        height,
        hMSL,
        hAcc,
        vAcc,
        velN,
        velE,
        velD,
        gSpeed,
        heading,
        sAcc,
        headingAcc,
        pDop,
        flags3,
        reserved2,
        reserved3
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static const std::size_t MsgMaxLen = Base::doMaxLength();
    static_assert(MsgMinLen == 84U, "Unexpected min serialisation length");
    static_assert(MsgMaxLen == 84U, "Unexpected max serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return cc_ublox::message::NavPvtCommon::name();
    }
};

} // namespace message

} // namespace cc_ublox
