// Generated by commsdsl2comms v6.3.0

/// @file
/// @brief Contains definition of <b>"TIM-VRFY (Poll)"</b> message and its fields.

#pragma once

#include <tuple>
#include "cc_ublox/MsgId.h"
#include "cc_ublox/message/TimVrfyPollCommon.h"
#include "cc_ublox/options/DefaultOptions.h"
#include "comms/MessageBase.h"

namespace cc_ublox
{

namespace message
{

/// @brief Fields of @ref TimVrfyPoll.
/// @tparam TOpt Extra options
/// @see @ref TimVrfyPoll
/// @headerfile cc_ublox/message/TimVrfyPoll.h
template <typename TOpt = cc_ublox::options::DefaultOptions>
struct TimVrfyPollFields
{
    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
    >;
};

/// @brief Definition of <b>"TIM-VRFY (Poll)"</b> message class.
/// @details
///     See @ref TimVrfyPollFields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile cc_ublox/message/TimVrfyPoll.h
template <typename TMsgBase, typename TOpt = cc_ublox::options::DefaultOptions>
class TimVrfyPoll : public
    comms::MessageBase<
        TMsgBase,
        typename TOpt::message::TimVrfyPoll,
        comms::option::def::StaticNumIdImpl<cc_ublox::MsgId_TimVrfy>,
        comms::option::def::FieldsImpl<typename TimVrfyPollFields<TOpt>::All>,
        comms::option::def::MsgType<TimVrfyPoll<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            typename TOpt::message::TimVrfyPoll,
            comms::option::def::StaticNumIdImpl<cc_ublox::MsgId_TimVrfy>,
            comms::option::def::FieldsImpl<typename TimVrfyPollFields<TOpt>::All>,
            comms::option::def::MsgType<TimVrfyPoll<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static const std::size_t MsgMaxLen = Base::doMaxLength();
    static_assert(MsgMinLen == 0U, "Unexpected min serialisation length");
    static_assert(MsgMaxLen == 0U, "Unexpected max serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return cc_ublox::message::TimVrfyPollCommon::name();
    }
};

} // namespace message

} // namespace cc_ublox
