// Generated by commsdsl2comms v7.0.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_ublox::message::TimVcocalStop message and its fields.

#pragma once

#include <cstdint>

namespace cc_ublox
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_ublox::message::TimVcocalStop message.
/// @see cc_ublox::message::TimVcocalStopFields
struct TimVcocalStopFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_ublox::message::TimVcocalStopFields::Type field.
    struct TypeCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_ublox::message::TimVcocalStopFields::Type field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_ublox::message::TimVcocalStopFields::Type field.
        static const char* name()
        {
            return "type";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };
};

/// @brief Common types and functions of 
///     @ref cc_ublox::message::TimVcocalStop message.
struct TimVcocalStopCommon
{
    /// @brief Name of the @ref cc_ublox::message::TimVcocalStop message.
    static const char* name()
    {
        return "TIM-VCOCAL (Stop)";
    }
};

} // namespace message

} // namespace cc_ublox
