// Generated by commsdsl2comms v5.1.2

/// @file
/// @brief Contains definition of <b>"UPD-SOS (Ack)"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "cc_ublox/MsgId.h"
#include "cc_ublox/field/FieldBase.h"
#include "cc_ublox/field/Res3.h"
#include "cc_ublox/message/UpdSosAckCommon.h"
#include "cc_ublox/options/DefaultOptions.h"
#include "comms/MessageBase.h"
#include "comms/field/EnumValue.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace cc_ublox
{

namespace message
{

/// @brief Fields of @ref UpdSosAck.
/// @tparam TOpt Extra options
/// @see @ref UpdSosAck
/// @headerfile cc_ublox/message/UpdSosAck.h
template <typename TOpt = cc_ublox::options::DefaultOptions>
struct UpdSosAckFields
{
    /// @brief Definition of <b>"cmd"</b> field.
    class Cmd : public
        comms::field::IntValue<
            cc_ublox::field::FieldBase<>,
            std::uint8_t,
            comms::option::def::FailOnInvalid<>,
            comms::option::def::DefaultNumValue<2>,
            comms::option::def::ValidNumValue<2>,
            comms::option::def::HasCustomRefresh
        >
    {
        using Base =
            comms::field::IntValue<
                cc_ublox::field::FieldBase<>,
                std::uint8_t,
                comms::option::def::FailOnInvalid<>,
                comms::option::def::DefaultNumValue<2>,
                comms::option::def::ValidNumValue<2>,
                comms::option::def::HasCustomRefresh
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::CmdCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::CmdCommon::name();
        }

        /// @brief Generated refresh functionality.
        bool refresh()
        {
            bool updated = Base::refresh();
            if (Base::valid()) {
                return updated;
            };
            Base::setValue(2);
            return true;
        }
    };

    /// @brief Definition of <b>"reserved1"</b> field.
    class Reserved1 : public
        cc_ublox::field::Res3<
            TOpt
        >
    {
        using Base =
            cc_ublox::field::Res3<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::Reserved1Common::name();
        }
    };

    /// @brief Definition of <b>"response"</b> field.
    /// @see @ref cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::ValueType
    class Response : public
        comms::field::EnumValue<
            cc_ublox::field::FieldBase<>,
            cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::ValueType,
            comms::option::def::ValidNumValueRange<0, 1>
        >
    {
        using Base =
            comms::field::EnumValue<
                cc_ublox::field::FieldBase<>,
                cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::ValueType,
                comms::option::def::ValidNumValueRange<0, 1>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Single value name info entry.
        using ValueNameInfo = cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::ValueNameInfo;

        /// @brief Type returned from @ref valueNamesMap() member function.
        /// @see @ref cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::ValueNamesMapInfo.
        using ValueNamesMapInfo = cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::ValueNamesMapInfo;

        /// @brief Retrieve name of the enum value.
        /// @see @ref cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::valueName().
        static const char* valueName(ValueType val)
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::valueName(val);
        }

        /// @brief Retrieve name of the enum value.
        /// @see @ref cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::valueName().
        static const char* valueNameOf(ValueType val)
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::valueName(val);
        }

        /// @brief Retrieve name of the @b current value
        const char* valueName() const
        {
            return valueName(Base::getValue());
        }

        /// @brief Retrieve map of enum value names.
        /// @see @ref cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::valueNamesMap().
        static ValueNamesMapInfo valueNamesMap()
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::valueNamesMap();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::ResponseCommon::name();
        }
    };

    /// @brief Definition of <b>"reserved2"</b> field.
    class Reserved2 : public
        cc_ublox::field::Res3<
            TOpt
        >
    {
        using Base =
            cc_ublox::field::Res3<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return cc_ublox::message::UpdSosAckFieldsCommon::Reserved2Common::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Cmd,
        Reserved1,
        Response,
        Reserved2
    >;
};

/// @brief Definition of <b>"UPD-SOS (Ack)"</b> message class.
/// @details
///     See @ref UpdSosAckFields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile cc_ublox/message/UpdSosAck.h
template <typename TMsgBase, typename TOpt = cc_ublox::options::DefaultOptions>
class UpdSosAck : public
    comms::MessageBase<
        TMsgBase,
        typename TOpt::message::UpdSosAck,
        comms::option::def::StaticNumIdImpl<cc_ublox::MsgId_UpdSos>,
        comms::option::def::FieldsImpl<typename UpdSosAckFields<TOpt>::All>,
        comms::option::def::MsgType<UpdSosAck<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            typename TOpt::message::UpdSosAck,
            comms::option::def::StaticNumIdImpl<cc_ublox::MsgId_UpdSos>,
            comms::option::def::FieldsImpl<typename UpdSosAckFields<TOpt>::All>,
            comms::option::def::MsgType<UpdSosAck<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_cmd index, @b Field_cmd type and @b field_cmd() access fuction
    ///         for @ref UpdSosAckFields::Cmd field.
    ///     @li @b FieldIdx_reserved1 index, @b Field_reserved1 type and @b field_reserved1() access fuction
    ///         for @ref UpdSosAckFields::Reserved1 field.
    ///     @li @b FieldIdx_response index, @b Field_response type and @b field_response() access fuction
    ///         for @ref UpdSosAckFields::Response field.
    ///     @li @b FieldIdx_reserved2 index, @b Field_reserved2 type and @b field_reserved2() access fuction
    ///         for @ref UpdSosAckFields::Reserved2 field.
    COMMS_MSG_FIELDS_NAMES(
        cmd,
        reserved1,
        response,
        reserved2
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static const std::size_t MsgMaxLen = Base::doMaxLength();
    static_assert(MsgMinLen == 8U, "Unexpected min serialisation length");
    static_assert(MsgMaxLen == 8U, "Unexpected max serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return cc_ublox::message::UpdSosAckCommon::name();
    }
};

} // namespace message

} // namespace cc_ublox
